bin(bm): create placeholders for subcommand add, out and view

diff --git a/bin/bm b/bin/bm
--- a/bin/bm
+++ b/bin/bm
@@ -4,8 +4,7 @@
 # Description: The URL bookmark manager (bm)
 # License: The Unlicense
 # Date created: July 02, 2025
-# Date modified: July 04, 2025
-# Template: https://github.com/xwmx/bash-boilerplate
+# Date modified: July 06, 2025
 
 # DESIGN COMMAND
 #
@@ -100,7 +99,7 @@ set -o nounset
 set -o errexit
 set -o pipefail
 
-trap 'echo "Error at line $LINENO. Exit code $?" >&2' ERR
+trap 'echo "Error at about line $LINENO. Exit code $?" >&2' ERR
 set -o errtrace
 
 IFS=$'\n\t'
@@ -115,14 +114,23 @@ _bm_file="${DOTFILES_PATH}/bookmark/bm.txt"
 # UTILITIES FUNCTIONS
 
 _exit_1() {
-  {
-    printf "%s: " "$(tput setaf 1)error$(tput sgr0)"
-    "${@}"
-  } 1>&2
+  printf "%s: %s\n" "$(tput setaf 1)Error$(tput sgr0)" "${*}" >&2
   exit 1
 }
 
 # CORE FUNCTIONS
+
+_add_bm() {
+  printf "TODO: add\n"
+}
+
+_out_bm() {
+  printf "TODO: out\n"
+}
+
+_view_bm() {
+  cat "${_bm_file}"
+}
 
 # MAIN
 
@@ -130,7 +138,7 @@ _main() {
   local subcmd="${1:-help}"
   case "${subcmd}" in
     add)
-      printf "TODO: add\n"
+      _add_bm
       ;;
     open)
       printf "TODO: open\n"
@@ -142,20 +150,19 @@ _main() {
       printf "TODO: rm\n"
       ;;
     out)
-      printf "TODO: out\n"
+      _out_bm
       ;;
     view)
-      cat "${_bm_file}"
+      _view_bm
       ;;
     help | --help | -h)
       printf "TODO: help\n"
       ;;
     *)
-      _exit_1 \
-        printf "unknown subcommand '%s'\nFor more information, try '%s help' or '%s -h\n" \
-        "${subcmd}" "${_cmd}" "${_cmd}"
+      _exit_1 "unknown subcommand '${subcmd}'." \
+        "For more information, try '${_cmd} help' or '${_cmd} -h'."
       ;;
   esac
 }
 
-_main "$@"
+_main "${@}"
